- hosts: tf-elasticsearch
  roles:
  - role: geerlingguy.java
  - role: geerlingguy.elasticsearch
    elasticsearch_version: '6.x'
    elasticsearch_network_host: 0.0.0.0
    elasticsearch_heap_size_min: 4g
    elasticsearch_heap_size_max: 4g
