---
- hosts: prometheus
  roles:
  - cloudalchemy.prometheus
  vars:
    prometheus_scrape_configs:
      - job_name: "prometheus"    # Custom scrape job, here using `static_config`
        metrics_path: "/metrics"
        static_configs:
          - targets:
              - "localhost:9090"
      - job_name: "netdata-scrape"
        metrics_path: "/api/v1/allmetrics"
        params:
          - format: "prometheus_all_hosts"
        honor_labels: true
        static_configs:
          - targets:
              - "netdata.internal.sickstack.com:19999"

- hosts: grafana
  roles:
    - cloudalchemy.grafana
  vars:
    grafana_datasources:
      - name: prometheus
        type: prometheus
        access: proxy
        url: 'http://localhost:9090'
        basicAuth: false

- hosts: webservers

  roles:
  - role: jdauphant.nginx
    nginx_user: "www-data"
    nginx_http_params:
      - sendfile "on"
      - server_names_hash_bucket_size 512
    nginx_sites:
      grafana.asininetech.net.http:
        - listen *:80
        - listen [::]:80
        - server_name grafana.asininetech.net
        - location /.well-known/acme-challenge/ {
            allow all;
          }
        - return 301 "https://$host$request_uri"
      grafana.asininetech.net.https:
        - listen *:443 ssl http2
        - listen [::]:443 ssl http2
        - server_name grafana.asininetech.net
        - access_log off
        - error_log "/var/log/nginx/grafana.asininetech.net.error.log"
        - ssl_certificate "/etc/ssl/letsencrypt/grafana.asininetech.net.crt"
        - ssl_certificate_key "/etc/ssl/letsencrypt/grafana.asininetech.net.pem"
        - add_header Strict-Transport-Security max-age=31536000
        - location / {
            proxy_pass http://grafana;
          }

    nginx_configs:
      gzip:
        - gzip on
        - gzip_disable msie6
        - gzip_vary on
        - gzip_proxied any
        - gzip_comp_level 6
        - gzip_buffers 16 8k
        - gzip_http_version 1.1
        - gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript
      upstream:
        - upstream grafana { server localhost:3000; keepalive 1024; }
      ssl:
        - ssl_protocols TLSv1.2
        - ssl_session_timeout 1d
        - ssl_session_cache shared:SSL:50m
        - ssl_session_tickets off
