---

- name: apply common configuration to all nodes
  hosts: unsetup
  user: root

  roles:
    - common
    - turn-off-motd-news
    - apt-maintenance
    - ssh-enforcement

- name: install PHP-FPM to required nodes
  hosts: php
  user: root

  roles:
    - php

- name: install MySQL server to required nodes
  hosts: mysql-servers
  user: root

  roles:
    - mysql

- name: install Icinga 2 for client usage
  hosts: icinga-clients
  user: root

  roles:
    - icinga-client

- name: install LEMP stack to required nodes
  hosts: lemp-servers
  user: root

  roles:
    - jdauphant.nginx
    - php
    - mysql

- name: Turn off MOTD news on Ubuntu 18.04 hosts
  hosts: myubuntunodes
  user: root

  roles:
    - turn-off-motd-news

- name: Set up unattended-upgrades for Ubuntu nodes
  hosts: myubuntunodes
  user: root

  roles:
    - apt-maintenance

- name: Deploy firewall rules
  hosts: firewalled
  user: root

  roles:
    - firewall-ruleset-deploy

- name: Install pgbackrest
  hosts: pgbackrest
  user: root

  roles:
    - pgbackrest-install

- name: Deploy ipset rulesets
  hosts: ipset
  user: root

  roles:
    - ipset-deploy

- name: SSH Enforcement
  hosts: cloud
  user: root

  roles:
    - ssh-enforcement
