---

- name: apply common configuration to all nodes
  hosts: unsetup
  user: root

  roles:
    - common

- name: install PHP-FPM to required nodes
  hosts: php
  user: root

  roles:
    - php

- name: install MySQL server to required nodes
  hosts: mysql-servers
  user: root

  roles:
    - mysql

- name: install Icinga 2 for client usage
  hosts: icinga-clients
  user: root

  roles:
    - icinga-client

- name: install LEMP stack to required nodes
  hosts: lemp-servers
  user: root

  roles:
    - jdauphant.nginx
    - php
    - mysql
