---

- name: apply common configuration to all nodes
  hosts: all
  user: root

  roles:
    - common

- name: install PHP-FPM to required nodes
  hosts: php
  user: root

  roles:
    - php

- name: Generate LE certs on required servers
  hosts: webservers
  user: root

  roles:
    - letsencrypt

- hosts: webservers

  roles:
  - role: jdauphant.nginx
    nginx_user: "www-data"
    nginx_http_params:
      - sendfile "on"
      - server_names_hash_bucket_size 512
    nginx_sites:
      asininetech.com.http:
        - listen {{ ansible_default_ipv4.address }}:80
        - listen [{{ ansible_default_ipv6.address }}]:80
        - server_name asininetech.com
        - return 301 "https://$host$request_uri"
      asininetech.com.https:
        - listen {{ ansible_default_ipv4.address }}:443 ssl http2
        - listen [{{ ansible_default_ipv6.address }}]:443 ssl http2
        - server_name asininetech.com
        - root "/srv/www/asininetech.com"
        - index index.php index.html
        - access_log "/var/log/nginx/asininetech.com.access.log"
        - error_log "/var/log/nginx/asininetech.com.error.log"
        - client_max_body_size 10M
        - ssl_certificate "/etc/letsencrypt/live/asininetech.com/fullchain.pem"
        - ssl_certificate_key "/etc/letsencrypt/live/asininetech.com/privkey.pem"
        - ssl_stapling on
        - resolver 8.8.8.8 valid=300s
        - add_header Strict-Transport-Security max-age=31536000
        - location / {
            try_files $uri $uri/ /index.php?$args;
          }
        - location ~* \.(js|css|png|jpg|jpeg|gif|ico)$ {
            expires 24h;
          }
        - location ~ \.php$ {
            try_files $uri =404;
            fastcgi_split_path_info ^(.+\.php)(/.+)$;
            include fastcgi_params;
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_pass php;
          }
      entropynet.net.http:
        - listen {{ ansible_default_ipv4.address }}:80
        - listen [{{ ansible_default_ipv6.address }}]:80
        - server_name entropynet.net
        - return 301 "https://$host$request_uri"
      entropynet.net.https:
        - listen {{ ansible_default_ipv4.address }}:443 ssl http2
        - listen [{{ ansible_default_ipv6.address }}]:443 ssl http2
        - server_name entropynet.net
        - root "/srv/www/entropynet.net"
        - error_page 404 /404.html 
        - index index.html
        - access_log "/var/log/nginx/entropynet.net.access.log"
        - error_log "/var/log/nginx/entropynet.net.error.log"
        - ssl_certificate "/etc/letsencrypt/live/entropynet.net/fullchain.pem"
        - ssl_certificate_key "/etc/letsencrypt/live/entropynet.net/privkey.pem"
        - ssl_stapling on
        - resolver 8.8.8.8 valid=300s
        - add_header Strict-Transport-Security max-age=31536000
      i.asininetech.com.http:
        - listen {{ ansible_default_ipv4.address }}:80
        - listen [{{ ansible_default_ipv6.address }}]:80
        - server_name i.asininetech.com
        - return 301 "https://$host$request_uri"
      i.asininetech.com.https:
        - listen {{ ansible_default_ipv4.address }}:443 ssl http2
        - listen [{{ ansible_default_ipv6.address }}]:443 ssl http2
        - server_name i.asininetech.com
        - root "/home/tenshi/public_html"
        - index index.html
        - access_log "/var/log/nginx/i.asininetech.com.access.log"
        - error_log "/var/log/nginx/i.asininetech.com.error.log"
        - ssl_certificate "/etc/letsencrypt/live/i.asininetech.com/fullchain.pem"
        - ssl_certificate_key "/etc/letsencrypt/live/i.asininetech.com/privkey.pem"
        - ssl_stapling on
        - resolver 8.8.8.8 valid=300s
        - location / {
            autoindex off;
            autoindex_exact_size off;
          }
        - add_header Strict-Transport-Security max-age=31536000
      sadiqsaif.ca:
        - listen {{ ansible_default_ipv4.address }}:80
        - listen {{ ansible_default_ipv4.address }}:443 ssl
        - listen [{{ ansible_default_ipv6.address }}]:80
        - listen [{{ ansible_default_ipv6.address }}]:443 ssl
        - server_name sadiqsaif.ca
        - access_log "/var/log/nginx/sadiqsaif.ca.access.log"
        - error_log "/var/log/nginx/sadiqsaif.ca.error.log"
        - ssl_certificate "/etc/letsencrypt/live/sadiqsaif.ca/fullchain.pem"
        - ssl_certificate_key "/etc/letsencrypt/live/sadiqsaif.ca/privkey.pem"
        - ssl_stapling on
        - resolver 8.8.8.8 valid=300s
        - add_header Strict-Transport-Security max-age=31536000
        - return 301 "https://sadiqsaif.com$request_uri"
      staticsafe.ca:
        - listen {{ ansible_default_ipv4.address }}:80
        - listen {{ ansible_default_ipv4.address }}:443 ssl
        - listen [{{ ansible_default_ipv6.address }}]:80
        - listen [{{ ansible_default_ipv6.address }}]:443 ssl
        - server_name staticsafe.ca
        - access_log "/var/log/nginx/staticsafe.ca.access.log"
        - error_log "/var/log/nginx/staticsafe.ca.error.log"
        - ssl_certificate "/etc/letsencrypt/live/staticsafe.ca/fullchain.pem"
        - ssl_certificate_key "/etc/letsencrypt/live/staticsafe.ca/privkey.pem"
        - ssl_stapling on
        - resolver 8.8.8.8 valid=300s
        - add_header Strict-Transport-Security max-age=31536000
        - return 301 "https://sadiqsaif.com$request_uri"
      twoshadesofbrown.com.http:
        - listen {{ ansible_default_ipv4.address }}:80
        - listen [{{ ansible_default_ipv6.address }}]:80
        - server_name twoshadesofbrown.com
        - return 301 "https://$host$request_uri"
      twoshadesofbrown.com.https:
        - listen {{ ansible_default_ipv4.address }}:443 ssl http2
        - listen [{{ ansible_default_ipv6.address }}]:443 ssl http2
        - server_name twoshadesofbrown.com
        - root "/srv/www/twoshadesofbrown.com"
        - index index.php index.html
        - access_log "/var/log/nginx/twoshadesofbrown.com.access.log"
        - error_log "/var/log/nginx/twoshadesofbrown.com.error.log"
        - client_max_body_size 10M
        - ssl_certificate "/etc/letsencrypt/live/twoshadesofbrown.com/fullchain.pem"
        - ssl_certificate_key "/etc/letsencrypt/live/twoshadesofbrown.com/privkey.pem"
        - ssl_stapling on
        - resolver 8.8.8.8 valid=300s
        - add_header Strict-Transport-Security max-age=31536000
        - location / {
            try_files $uri $uri/ /index.php?$args;
          }
        - location ~* \.(js|css|png|jpg|jpeg|gif|ico)$ {
            expires 24h;
          }
        - location ~ \.php$ {
            try_files $uri =404;
            fastcgi_split_path_info ^(.+\.php)(/.+)$;
            include fastcgi_params;
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_pass php;
          }
      wiki.staticsafe.ca.http:
        - listen {{ ansible_default_ipv4.address }}:80
        - listen [{{ ansible_default_ipv6.address }}]:80
        - server_name wiki.staticsafe.ca
        - return 301 "https://$host$request_uri"
      wiki.staticsafe.ca.https:
        - listen {{ ansible_default_ipv4.address }}:443 ssl http2
        - listen [{{ ansible_default_ipv6.address }}]:443 ssl http2
        - server_name wiki.staticsafe.ca
        - root "/srv/www/wiki.staticsafe.ca"
        - index index.php
        - access_log "/var/log/nginx/wiki.staticsafe.ca.access.log"
        - error_log "/var/log/nginx/wiki.staticsafe.ca.error.log"
        - ssl_certificate "/etc/letsencrypt/live/wiki.staticsafe.ca/fullchain.pem"
        - ssl_certificate_key "/etc/letsencrypt/live/wiki.staticsafe.ca/privkey.pem"
        - ssl_stapling on
        - resolver 8.8.8.8 valid=300s
        - add_header Strict-Transport-Security max-age=31536000
        - location ~ /(data|conf|bin|inc)/ {
            deny all;
          }
        - location / {
            try_files $uri $uri/ /index.php?$args;
          }
        - location ~ \.php$ {
            try_files $uri =404;
            fastcgi_split_path_info ^(.+\.php)(/.+)$;
            include fastcgi_params;
            fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
            fastcgi_pass php;
            fastcgi_index index.php;
          }
      sadiqsaif.com.http:
        - listen {{ ansible_default_ipv4.address }}:80
        - listen [{{ ansible_default_ipv6.address }}]:80
        - server_name sadiqsaif.com
        - return 301 "https://$host$request_uri"
      sadiqsaif.com.https:
        - listen {{ ansible_default_ipv4.address }}:443 ssl http2
        - listen [{{ ansible_default_ipv6.address }}]:443 ssl http2
        - server_name sadiqsaif.com
        - root "/srv/www/sadiqsaif.com"
        - index index.html
        - access_log "/var/log/nginx/sadiqsaif.com.access.log"
        - error_log "/var/log/nginx/sadiqsaif.com.error.log"
        - ssl_certificate "/etc/letsencrypt/live/sadiqsaif.com/fullchain.pem"
        - ssl_certificate_key "/etc/letsencrypt/live/sadiqsaif.com/privkey.pem"
        - ssl_stapling on
        - resolver 8.8.8.8 valid=300s
        - add_header Strict-Transport-Security max-age=31536000
        - error_page 404 /404.html
    nginx_configs:
      gzip:
        - gzip on
        - gzip_disable msie6
        - gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript
      upstream:
        - upstream php { server unix:/run/php/php7.0-fpm.sock; }
      ssl:
        - ssl_protocols TLSv1.2
        - ssl_prefer_server_ciphers on
        - ssl_ciphers 'ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256'
        - ssl_dhparam "/etc/nginx/dhparams.pem"
        - ssl_session_timeout 1d
        - ssl_session_cache shared:SSL:50m
        - ssl_session_tickets off
