---
# This role installs Icinga 2 and the plugins required on a Icinga client nodes

- name: Add Icinga package repository key
  apt_key: url="https://packages.icinga.com/icinga.key" state=present
- name: Add Icinga apt repository
  apt_repository: repo="https://packages.icinga.com/ubuntu icinga-xenial main" state=present
- name: Update apt cache and install Icinga packages
  apt: name={{ item }} state=latest update_cache=yes
  with_items:
     - icinga2
     - monitoring-plugins
- name: Ensure that icinga2 systemd service is enabled
  systemd:
    name: icinga2
    enabled: yes
