---
# This task sets up unattended-upgrade's config

- name: Install unattended-upgrade and apt-listchanges
  apt: name={{ packages }} state=latest update_cache=yes
  vars:
    packages:
      - unattended-upgrades
      - apt-listchanges

- name: Copy our 50unattended-upgrades
  copy:
    src: 50unattended-upgrades
    dest: /etc/apt/apt.conf.d/50unattended-upgrades

- name: Ensure 20auto-upgrades has the correct values using debconf
  debconf:
    name: unattended-upgrades
    question: unattended-upgrades/enable_auto_updates
    vtype: boolean
    value: true
